/**
 * @file role-details.ts
 * @description Predefined role metadata and permissions (single source of truth for API and UI)
 * @module lib/auth
 */

import { PERMISSIONS } from '@/lib/auth/permissions'

export const ROLE_DETAILS: Record<
  string,
  { name: string; description: string; permissions: string[] }
> = {
  ADMIN: {
    name: 'Admin',
    description: 'Full operational access',
    permissions: Object.values(PERMISSIONS).filter(
      (p) =>
        ![
          'system.read_only_mode',
          'system.clear_cache',
          'system.view_logs',
          'user.delete',
        ].includes(p)
    ),
  },
  SALES_MANAGER: {
    name: 'Sales Manager',
    description: 'Manage sales, bookings, quotes, clients',
    permissions: [
      'booking.create',
      'booking.read',
      'booking.update',
      'booking.delete',
      'booking.cancel',
      'booking.transition',
      'quote.create',
      'quote.read',
      'quote.update',
      'quote.convert',
      'quote.delete',
      'client.create',
      'client.read',
      'client.update',
      'client.delete',
      'contract.create',
      'contract.read',
      'contract.update',
      'contract.sign',
      'invoice.read',
      'invoice.create',
      'payment.read',
      'payment.create',
      'equipment.read',
      'reports.read',
      'reports.export',
      'dashboard.read',
      'dashboard.analytics',
      'ai.use',
      'ai.risk_assessment',
      'ai.kit_builder',
      'ai.pricing',
      'ai.demand_forecast',
      'ai.chatbot',
      'kit.read',
      'pricing.read',
      'studio.read',
    ],
  },
  ACCOUNTANT: {
    name: 'Accountant',
    description: 'Financial operations and reporting',
    permissions: [
      'invoice.create',
      'invoice.read',
      'invoice.update',
      'invoice.delete',
      'invoice.mark_paid',
      'invoice.generate_zatca',
      'payment.create',
      'payment.read',
      'payment.refund',
      'payment.verify',
      'payment.mark_paid',
      'booking.read',
      'booking.update',
      'client.read',
      'contract.read',
      'quote.read',
      'reports.read',
      'reports.export',
      'dashboard.read',
      'dashboard.analytics',
      'audit.read',
      'audit.export',
    ],
  },
  WAREHOUSE_MANAGER: {
    name: 'Warehouse Manager',
    description: 'Equipment and inventory management',
    permissions: [
      'equipment.create',
      'equipment.read',
      'equipment.update',
      'equipment.delete',
      'equipment.checkout',
      'equipment.checkin',
      'warehouse.read',
      'warehouse.check_in',
      'warehouse.check_out',
      'warehouse.inventory',
      'maintenance.create',
      'maintenance.read',
      'maintenance.update',
      'maintenance.complete',
      'maintenance.delete',
      'booking.read',
      'booking.update',
      'delivery.read',
      'delivery.assign',
      'category.read',
      'brand.read',
      'studio.read',
      'dashboard.read',
      'import.create',
      'import.read',
    ],
  },
  TECHNICIAN: {
    name: 'Technician',
    description: 'Equipment maintenance and inspection',
    permissions: [
      'equipment.read',
      'equipment.update',
      'maintenance.create',
      'maintenance.read',
      'maintenance.update',
      'maintenance.complete',
      'warehouse.read',
      'dashboard.read',
    ],
  },
  CUSTOMER_SERVICE: {
    name: 'Customer Service',
    description: 'Customer support and basic operations',
    permissions: [
      'booking.create',
      'booking.read',
      'booking.update',
      'quote.create',
      'quote.read',
      'quote.update',
      'client.create',
      'client.read',
      'client.update',
      'contract.read',
      'contract.create',
      'invoice.read',
      'payment.read',
      'equipment.read',
      'dashboard.read',
      'ai.chatbot',
      'ai.use',
    ],
  },
  MARKETING_MANAGER: {
    name: 'Marketing Manager',
    description: 'Marketing campaigns and analytics',
    permissions: [
      'marketing.create',
      'marketing.read',
      'marketing.update',
      'marketing.send',
      'marketing.delete',
      'coupon.create',
      'coupon.read',
      'coupon.update',
      'coupon.delete',
      'cms.studio.read',
      'cms.studio.update',
      'client.read',
      'booking.read',
      'reports.read',
      'reports.export',
      'dashboard.read',
      'dashboard.analytics',
      'ai.demand_forecast',
    ],
  },
  RISK_MANAGER: {
    name: 'Risk Manager',
    description: 'Risk assessment and approvals',
    permissions: [
      'approval.read',
      'approval.approve',
      'approval.reject',
      'approval.delegate',
      'booking.read',
      'booking.transition',
      'client.read',
      'client.blacklist',
      'payment.read',
      'payment.verify',
      'ai.risk_assessment',
      'audit.read',
      'audit.search',
      'dashboard.read',
      'dashboard.analytics',
      'reports.read',
    ],
  },
  APPROVAL_AGENT: {
    name: 'Approval Agent',
    description: 'Process approval requests',
    permissions: [
      'approval.read',
      'approval.approve',
      'approval.reject',
      'approval.delegate',
      'booking.read',
      'payment.read',
      'invoice.read',
      'client.read',
      'dashboard.read',
    ],
  },
  AUDITOR: {
    name: 'Auditor',
    description: 'Read-only access for auditing',
    permissions: [
      'booking.read',
      'equipment.read',
      'payment.read',
      'client.read',
      'invoice.read',
      'contract.read',
      'quote.read',
      'maintenance.read',
      'coupon.read',
      'marketing.read',
      'audit.read',
      'audit.export',
      'audit.search',
      'reports.read',
      'reports.export',
      'dashboard.read',
      'dashboard.analytics',
      'studio.read',
      'category.read',
      'brand.read',
    ],
  },
  AI_OPERATOR: {
    name: 'AI Operator',
    description: 'AI features and automation',
    permissions: [
      'ai.use',
      'ai.risk_assessment',
      'ai.kit_builder',
      'ai.pricing',
      'ai.demand_forecast',
      'ai.chatbot',
      'kit.create',
      'kit.read',
      'kit.update',
      'kit.delete',
      'pricing.create',
      'pricing.read',
      'pricing.update',
      'pricing.delete',
      'booking.read',
      'equipment.read',
      'client.read',
      'reports.read',
      'dashboard.read',
      'dashboard.analytics',
    ],
  },
  DATA_ENTRY: {
    name: 'Data Entry',
    description: 'Equipment metadata and SEO content only',
    permissions: [
      'equipment.create',
      'equipment.read',
      'equipment.update_metadata',
      'category.create',
      'category.read',
      'category.update',
      'category.delete',
      'brand.create',
      'brand.read',
      'brand.update',
      'brand.delete',
      'seo.edit_meta_titles',
      'seo.edit_meta_descriptions',
      'seo.edit_slugs',
      'seo.edit_alt_text',
      'studio.read',
      'studio.update',
    ],
  },
}

export function getRoleDetails(
  roleId: string
): { name: string; description: string; permissions: string[] } | null {
  return ROLE_DETAILS[roleId] ?? null
}
