-- Add Studio and related columns that may be missing (from 20260221095309 that was skipped)
ALTER TABLE "Studio" ADD COLUMN IF NOT EXISTS "bookingCountDisplay" INTEGER;
ALTER TABLE "Studio" ADD COLUMN IF NOT EXISTS "discountActive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Studio" ADD COLUMN IF NOT EXISTS "discountMessage" TEXT;
ALTER TABLE "Studio" ADD COLUMN IF NOT EXISTS "discountPercent" INTEGER;
ALTER TABLE "Studio" ADD COLUMN IF NOT EXISTS "hasWifi" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Studio" ADD COLUMN IF NOT EXISTS "heroTagline" TEXT;

ALTER TABLE "StudioAddOn" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "StudioAddOn" ADD COLUMN IF NOT EXISTS "iconName" TEXT;
ALTER TABLE "StudioAddOn" ADD COLUMN IF NOT EXISTS "originalPrice" DECIMAL(10,2);
ALTER TABLE "StudioAddOn" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "StudioPackage" ADD COLUMN IF NOT EXISTS "badgeText" TEXT;
ALTER TABLE "StudioPackage" ADD COLUMN IF NOT EXISTS "descriptionAr" TEXT;
ALTER TABLE "StudioPackage" ADD COLUMN IF NOT EXISTS "nameZh" TEXT;
ALTER TABLE "StudioPackage" ADD COLUMN IF NOT EXISTS "recommended" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "appliedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "totalImpact" DECIMAL(12,2);

ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "applicableStudioIds" JSONB;
