/**
 * Category-specific spec field templates for cinema equipment.
 * Used by SpecParserService to know which specs to infer per category.
 * Comprehensive templates covering all professional-grade technical details.
 */

export const CATEGORY_SPEC_TEMPLATES: Record<string, string[]> = {
  Cameras: [
    // Sensor & Image
    'sensor_size',
    'sensor_type',
    'effective_pixels',
    'resolution',
    'max_photo_resolution',
    'aspect_ratio',
    'bit_depth',
    'color_sampling',
    'dynamic_range_stops',
    'dual_native_iso',
    'base_iso',
    'max_iso',
    'color_science',
    // Video Performance
    'max_video_resolution',
    'max_framerate',
    'max_framerate_4k',
    'max_framerate_1080p',
    'slow_motion',
    'codec',
    'internal_codec',
    'external_codec',
    'raw_recording',
    'log_gamma',
    'hdr_mode',
    'rolling_shutter',
    // Autofocus & Stabilization
    'autofocus',
    'af_type',
    'af_points',
    'face_eye_tracking',
    'ibis',
    'ibis_stops',
    // Lens & Mount
    'mount_type',
    'built_in_nd',
    'nd_stops',
    'flange_distance',
    // Connectivity & I/O
    'sdi_output',
    'hdmi_output',
    'hdmi_version',
    'timecode_io',
    'genlock',
    'audio_inputs',
    'audio_input_type',
    'headphone_jack',
    'speaker',
    'usb_type',
    'ethernet',
    'wifi',
    'bluetooth',
    'wireless_video',
    'remote_control',
    // Recording Media
    'media_type',
    'card_slots',
    'max_card_speed',
    'internal_storage',
    // Display & Viewfinder
    'lcd_size',
    'lcd_resolution',
    'lcd_type',
    'lcd_touchscreen',
    'lcd_articulating',
    'evf_resolution',
    'evf_magnification',
    // Power & Battery
    'battery_type',
    'battery_life_minutes',
    'usb_charging',
    'power_draw_watts',
    'dc_input',
    'v_mount_plate',
    // Physical & Build
    'weight_kg',
    'weight_body_only',
    'dimensions_cm',
    'body_material',
    'weather_sealed',
    'operating_temp',
    'humidity_range',
    // Tally & Control
    'tally_light',
    'control_protocol',
    'multi_cam_sync',
  ],
  Lenses: [
    // Optical Core
    'focal_length',
    'focal_length_range',
    'max_aperture',
    'min_aperture',
    'aperture_range',
    'lens_type',
    'zoom_ratio',
    'optical_design',
    'elements_groups',
    'special_elements',
    'coating',
    'coating_type',
    // Mount & Compatibility
    'mount_type',
    'image_circle',
    'sensor_coverage',
    'flange_distance',
    'compatible_cameras',
    // Focus
    'minimum_focus_distance',
    'focus_throw',
    'focus_type',
    'focus_motor',
    'focus_breathing',
    'parfocal',
    'macro_capability',
    'magnification_ratio',
    // Iris & Aperture
    'blade_count',
    'blade_type',
    'iris_geared',
    'iris_de_click',
    't_stop',
    // Image Quality
    'sharpness_center',
    'chromatic_aberration',
    'distortion',
    'vignetting',
    'bokeh_quality',
    'flare_control',
    'breathing_control',
    // Physical
    'filter_size',
    'front_diameter',
    'weight_kg',
    'length_mm',
    'dimensions_cm',
    'barrel_material',
    'weather_sealed',
    'focus_ring_rotation',
    'gear_pitch',
    'front_rotation',
    // Accessories
    'lens_hood_included',
    'case_included',
    'support_foot',
  ],
  Lighting: [
    // Light Output
    'type',
    'light_source',
    'led_type',
    'power_watts',
    'max_output_watts',
    'output_lux_1m',
    'output_lux_3m',
    'output_lux_5m',
    'output_fc_1m',
    'output_lumens',
    // Color
    'color_temp',
    'color_temp_range',
    'cri',
    'tlci',
    'cqs',
    'ssi',
    'color_accuracy',
    'green_magenta_shift',
    'gel_correction',
    'rgb_mode',
    'hsi_mode',
    'xy_coordinate',
    'color_presets',
    // Beam & Optics
    'beam_angle',
    'beam_angle_range',
    'field_angle',
    'fresnel_lens',
    'diffusion',
    'barn_doors',
    'front_accessory_mount',
    'bowens_mount',
    'modifier_compatibility',
    // Dimming & Control
    'dimming_range',
    'dimming_curve',
    'flicker_free_hz',
    'strobe_mode',
    'lightning_effect',
    'special_effects',
    'dmx_channels',
    'dmx_modes',
    'wireless_protocol',
    'wireless_range',
    'app_control',
    'bluetooth',
    'art_net',
    'sacn',
    // Power
    'ac_input',
    'dc_input',
    'power_consumption',
    'battery_plate',
    'battery_type',
    'battery_runtime',
    'v_mount',
    'gold_mount',
    // Physical
    'weight_kg',
    'weight_with_yoke',
    'dimensions_cm',
    'yoke_type',
    'fixture_mount',
    'clamp_diameter',
    'cooling_type',
    'noise_level_db',
    'ip_rating',
    'operating_temp',
    'body_material',
    'certifications',
  ],
  Audio: [
    // Microphone Specs
    'type',
    'transducer_type',
    'capsule_size',
    'polar_pattern',
    'switchable_patterns',
    'frequency_response',
    'frequency_range_hz',
    'sensitivity_dbv',
    'self_noise_db',
    'max_spl_db',
    'signal_to_noise_ratio',
    'dynamic_range_db',
    'impedance_ohms',
    'thd',
    'pad_switch',
    'hpf_switch',
    'hpf_frequency',
    // Connectivity
    'connector_type',
    'output_type',
    'phantom_power',
    'phantom_voltage',
    'plug_in_power',
    'cable_length',
    'cable_type',
    // Wireless (for wireless systems)
    'wireless_type',
    'wireless_range_m',
    'frequency_band',
    'frequency_range_mhz',
    'channels_available',
    'simultaneous_systems',
    'latency_ms',
    'encryption',
    'transmitter_type',
    'receiver_type',
    'antenna_type',
    'rf_power',
    // Recorder (for field recorders)
    'recording_channels',
    'max_sample_rate',
    'max_bit_depth',
    'recording_format',
    'media_type',
    'preamp_type',
    'preamp_gain_db',
    'limiter',
    'mixer_channels',
    'phantom_channels',
    'timecode',
    'timecode_io',
    // Physical
    'weight_kg',
    'dimensions_cm',
    'body_material',
    'shock_mount_included',
    'windscreen_included',
    'mount_type',
    'battery_type',
    'battery_life_hours',
    'phantom_power_hours',
    'usb_power',
    'operating_temp',
  ],
  Grip: [
    // Load & Support
    'max_load_kg',
    'counterbalance_range',
    'counterbalance_type',
    'payload_range',
    // Height & Reach
    'max_height_cm',
    'min_height_cm',
    'max_operating_height',
    'center_column_height',
    'arm_reach',
    'boom_length',
    // Head
    'head_type',
    'fluid_head',
    'pan_range',
    'tilt_range',
    'pan_drag',
    'tilt_drag',
    'quick_release',
    'quick_release_type',
    'leveling_ball',
    'bowl_size',
    // Legs & Base
    'leg_sections',
    'leg_type',
    'leg_lock_type',
    'spreader_type',
    'spiked_feet',
    'rubber_feet',
    'caster_wheels',
    // Physical
    'weight_kg',
    'weight_head_only',
    'weight_legs_only',
    'folded_length_cm',
    'transport_length',
    'material',
    'body_material',
    'operating_temp',
    // Stabilizer Specific
    'axis_count',
    'stabilization_type',
    'follow_modes',
    'motor_torque',
    'controllable_range_pan',
    'controllable_range_tilt',
    'controllable_range_roll',
    'battery_life_hours',
    'battery_type',
    'charging_time',
    'app_control',
  ],
  Monitors: [
    // Display
    'screen_size',
    'resolution',
    'pixel_density_ppi',
    'panel_type',
    'color_depth',
    'aspect_ratio',
    'viewing_angle',
    // Brightness & HDR
    'brightness_nits',
    'contrast_ratio',
    'hdr_support',
    'hdr_format',
    // Color
    'color_space',
    'color_gamut_dcip3',
    'color_gamut_rec709',
    'color_gamut_rec2020',
    'delta_e',
    'calibration',
    'factory_calibrated',
    '3d_lut',
    'lut_support',
    'lut_slots',
    'false_color',
    'zebra',
    'focus_peaking',
    'waveform',
    'vectorscope',
    'histogram',
    'anamorphic_desqueeze',
    'pixel_zoom',
    'image_flip',
    // Inputs
    'hdmi_input',
    'hdmi_version',
    'sdi_input',
    'sdi_standard',
    'max_input_resolution',
    'max_input_framerate',
    'cross_conversion',
    // Outputs
    'hdmi_output',
    'sdi_output',
    'headphone_out',
    'speaker',
    // Touch & Control
    'touch_screen',
    'touch_type',
    'gesture_control',
    'physical_buttons',
    'assignable_buttons',
    'menu_language',
    // Power & Physical
    'battery_type',
    'battery_plate',
    'battery_life_hours',
    'dc_input',
    'power_consumption',
    'weight_kg',
    'dimensions_cm',
    'mount_points',
    'tilt_arm',
    'sunhood_included',
    'operating_temp',
    'body_material',
  ],
  Stabilizers: [
    'axis_count',
    'max_payload_kg',
    'min_payload_kg',
    'stabilization_type',
    'follow_modes',
    'motor_torque',
    'controllable_range_pan',
    'controllable_range_tilt',
    'controllable_range_roll',
    'max_speed',
    'quick_release_type',
    'mounting_plate',
    'joystick_type',
    'trigger_button',
    'focus_motor_included',
    'focus_control',
    'app_control',
    'bluetooth',
    'wifi',
    'battery_type',
    'battery_life_hours',
    'charging_time',
    'usb_charging',
    'weight_kg',
    'dimensions_cm',
    'folded_dimensions',
    'body_material',
    'underslung_mode',
    'inception_mode',
    'timelapse_mode',
    'panorama_mode',
    'sport_mode',
    'operating_temp',
  ],
  Drones: [
    'max_flight_time_min',
    'max_speed_kmh',
    'max_wind_resistance',
    'max_altitude_m',
    'max_transmission_range',
    'transmission_system',
    'gps_systems',
    'obstacle_sensing',
    'obstacle_avoidance',
    'camera_sensor_size',
    'camera_resolution',
    'max_video_resolution',
    'max_framerate',
    'max_bitrate',
    'codec',
    'hdr_recording',
    'gimbal_axis',
    'gimbal_range',
    'gimbal_stabilization',
    'adjustable_aperture',
    'nd_filter_included',
    'intelligent_flight_modes',
    'tracking_modes',
    'hyperlapse',
    'panorama_modes',
    'battery_type',
    'battery_capacity_mah',
    'charging_time',
    'weight_kg',
    'folded_dimensions',
    'unfolded_dimensions',
    'propeller_type',
    'noise_level_db',
    'operating_temp',
    'ip_rating',
    'remote_controller_type',
    'controller_screen',
    'internal_storage_gb',
    'media_type',
  ],
  Power: [
    'battery_type',
    'chemistry',
    'voltage',
    'capacity_wh',
    'capacity_mah',
    'max_draw_amps',
    'max_output_watts',
    'mount_type',
    'd_tap_outputs',
    'usb_a_outputs',
    'usb_c_outputs',
    'usb_c_pd_watts',
    'regulated_outputs',
    'led_indicator',
    'fuel_gauge',
    'charge_time_hours',
    'charger_included',
    'stackable',
    'hot_swappable',
    'weight_kg',
    'dimensions_cm',
    'operating_temp',
    'certifications',
    'flight_safe',
  ],
  Recorders: [
    'recording_channels',
    'max_resolution',
    'max_framerate',
    'codec',
    'raw_support',
    'prores_support',
    'dnxhd_support',
    'bit_depth',
    'color_sampling',
    'hdmi_input',
    'sdi_input',
    'sdi_output',
    'hdmi_output',
    'analog_input',
    'audio_channels',
    'audio_bit_depth',
    'audio_sample_rate',
    'timecode_io',
    'genlock',
    'media_type',
    'media_slots',
    'screen_size',
    'screen_resolution',
    'touch_screen',
    'waveform',
    'vectorscope',
    'false_color',
    'focus_peaking',
    'lut_support',
    'playback',
    'battery_type',
    'battery_life_hours',
    'dc_input',
    'power_consumption',
    'weight_kg',
    'dimensions_cm',
    'mount_points',
    'operating_temp',
  ],
  Wireless: [
    'type',
    'frequency_band',
    'frequency_range_mhz',
    'max_range_m',
    'max_range_los',
    'latency_ms',
    'max_resolution',
    'max_framerate',
    'codec',
    'bit_depth',
    'hdmi_input',
    'hdmi_output',
    'sdi_input',
    'sdi_output',
    'simultaneous_receivers',
    'multicast_support',
    'encryption',
    'channel_selection',
    'auto_scan',
    'antenna_type',
    'antenna_count',
    'mounting_options',
    'battery_type',
    'battery_life_hours',
    'usb_power',
    'dc_input',
    'weight_transmitter_kg',
    'weight_receiver_kg',
    'dimensions_transmitter',
    'dimensions_receiver',
    'operating_temp',
    'certifications',
  ],
  Accessories: [
    'type',
    'compatibility',
    'material',
    'weight_kg',
    'dimensions_cm',
    'color',
    'mounting_type',
    'thread_size',
    'quick_release',
    'adjustable',
    'max_load_kg',
    'included_accessories',
    'warranty',
  ],
}

/**
 * Extended category aliases to match various category names to templates
 */
const CATEGORY_ALIASES: Record<string, string> = {
  'camera': 'Cameras',
  'cameras': 'Cameras',
  'cinema camera': 'Cameras',
  'cinema cameras': 'Cameras',
  'video camera': 'Cameras',
  'camcorder': 'Cameras',
  'mirrorless': 'Cameras',
  'dslr': 'Cameras',
  'lens': 'Lenses',
  'lenses': 'Lenses',
  'cinema lens': 'Lenses',
  'cinema lenses': 'Lenses',
  'prime lens': 'Lenses',
  'zoom lens': 'Lenses',
  'anamorphic': 'Lenses',
  'light': 'Lighting',
  'lights': 'Lighting',
  'lighting': 'Lighting',
  'led light': 'Lighting',
  'led panel': 'Lighting',
  'fresnel': 'Lighting',
  'strobe': 'Lighting',
  'flash': 'Lighting',
  'audio': 'Audio',
  'microphone': 'Audio',
  'microphones': 'Audio',
  'mic': 'Audio',
  'wireless mic': 'Audio',
  'recorder': 'Audio',
  'field recorder': 'Audio',
  'sound': 'Audio',
  'grip': 'Grip',
  'tripod': 'Grip',
  'tripods': 'Grip',
  'support': 'Grip',
  'heads': 'Grip',
  'fluid head': 'Grip',
  'slider': 'Grip',
  'jib': 'Grip',
  'dolly': 'Grip',
  'monitor': 'Monitors',
  'monitors': 'Monitors',
  'field monitor': 'Monitors',
  'on-camera monitor': 'Monitors',
  'reference monitor': 'Monitors',
  'stabilizer': 'Stabilizers',
  'stabilizers': 'Stabilizers',
  'gimbal': 'Stabilizers',
  'gimbals': 'Stabilizers',
  'steadicam': 'Stabilizers',
  'drone': 'Drones',
  'drones': 'Drones',
  'uav': 'Drones',
  'fpv': 'Drones',
  'power': 'Power',
  'battery': 'Power',
  'batteries': 'Power',
  'charger': 'Power',
  'power supply': 'Power',
  'video recorder': 'Recorders',
  'video recorders': 'Recorders',
  'external recorder': 'Recorders',
  'ssd recorder': 'Recorders',
  'wireless': 'Wireless',
  'wireless video': 'Wireless',
  'video transmitter': 'Wireless',
  'wireless system': 'Wireless',
  'accessory': 'Accessories',
  'accessories': 'Accessories',
  'cage': 'Accessories',
  'rig': 'Accessories',
  'follow focus': 'Accessories',
  'matte box': 'Accessories',
  'filter': 'Accessories',
  'filters': 'Accessories',
}

export function getExpectedSpecs(categoryName: string): string[] {
  const direct = CATEGORY_SPEC_TEMPLATES[categoryName]
  if (direct) return direct

  const alias = CATEGORY_ALIASES[categoryName.toLowerCase()]
  if (alias) return CATEGORY_SPEC_TEMPLATES[alias] ?? []

  // Fuzzy match: check if category name contains a known key
  for (const [key, templateName] of Object.entries(CATEGORY_ALIASES)) {
    if (categoryName.toLowerCase().includes(key)) {
      return CATEGORY_SPEC_TEMPLATES[templateName] ?? []
    }
  }

  return [
    'type',
    'weight_kg',
    'dimensions_cm',
    'power_source',
    'material',
    'compatibility',
    'max_load_kg',
    'operating_temp',
    'certifications',
  ]
}

/**
 * Get the resolved category template name for structured spec generation
 */
export function resolveTemplateName(categoryName: string): string {
  if (CATEGORY_SPEC_TEMPLATES[categoryName]) return categoryName
  const alias = CATEGORY_ALIASES[categoryName.toLowerCase()]
  if (alias) return alias
  for (const [key, templateName] of Object.entries(CATEGORY_ALIASES)) {
    if (categoryName.toLowerCase().includes(key)) return templateName
  }
  return categoryName
}
