-- Add Product columns that may be missing (from 20260221095309 that was skipped)
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "aiContentFlags" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "aiReviewReason" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "aiRunCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "contentQualityScore" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "contentScore" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "contentScoreAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "lastAiRunAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "needsAiReview" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "photoStatus" TEXT DEFAULT 'unknown';
